---
os: linux
dist: xenial  # Python3.7 virtualenv is available only on Travis Xenial VMs.
language: go
sudo: true
go:
  - "1.13"
env:
  - GO111MODULE=on
before_install:
  - sudo apt-get update -q
  - sudo apt-get install -y python3 python3-dev python3-pip python3-setuptools
  - sudo pip3 install -r scripts/requirements.txt
install:
  - true # just skip
script:
  - go test -v
after_success:
  - test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash
  - test -n "$TRAVIS_TAG" && python3 -u scripts/upload2qiniu.py